<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE etym [
<!ELEMENT etym (tree+)>
<!ELEMENT tree (lang,text+,morpheme+,def,word+)>
<!ELEMENT lang (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT morpheme (#PCDATA)>
<!ELEMENT def (#PCDATA)>
<!ELEMENT word (lang,text+,morpheme+,def,word*)>
<!ATTLIST tree id CDATA #REQUIRED>
]>
<!-- This file provides for some test cases: 
	 1) A word is found multiple times in the same tree (ros)
	 2) A word is found in multiple trees (biology)
	 -->
<etym>
	<tree id='1'>
		<lang>PIE</lang>
		<text>khursa</text>
		<morpheme>khursa</morpheme>
		<def>Some kinda animal</def>
		<word>
			<lang>Old English</lang>
			<text>hors</text>
			<morpheme>hors</morpheme>
			<def>A man-eating beast</def>
			<word>
				<lang>Middle English</lang>
				<text>horse</text>
				<text>hors</text>
				<text>horce</text>
				<text>horsse</text>
				<text>horis</text>
				<text>hos</text>
				<text>ors</text>
				<morpheme>horse</morpheme>
				<def>A horse that you feed oats</def>
				<word>
					<lang>Modern English</lang>
					<text>horse</text>
					<morpheme>horse</morpheme>
					<def>A horse that you ride</def>
				</word>
			</word>
		</word>
		<word>
			<lang>Old High German</lang>
			<text>ros</text>
			<text>hros</text>
			<morpheme>ros</morpheme>
			<morpheme>hros</morpheme>
			<def>Eine Bestie</def>
			<word>
				<lang>Middle High German</lang>
				<text>ros</text>
				<morpheme>ros</morpheme>
				<def>Eines infizierten Tieres</def>
				<word>
					<lang>Modern German</lang>
					<text>ross</text>
					<morpheme>ross</morpheme>
					<def>Eine blutr√ºnstige Monster</def>
				</word>
			</word>
		</word>
	</tree>
	<tree id='2'>
		<lang>PIE</lang>
		<text>gweie</text>
		<morpheme>gweie</morpheme>
		<def>Lifey stuff</def>
		<word>
			<lang>Greek</lang>
			<text>bios</text>
			<morpheme>bios</morpheme>
			<def>Life</def>
			<word>
				<lang>Modern English</lang>
				<text>biology</text>
				<morpheme>bio</morpheme>
				<def>Study of life</def>
			</word>
		</word>
	</tree>
	<tree id='3'>
		<lang>PIE</lang>
		<text>leg</text>
		<morpheme>leg</morpheme>
		<def>Wibbly-wobbly timey-wimey</def>
		<word>
			<lang>Greek</lang>
			<text>logia</text>
			<morpheme>logia</morpheme>
			<def>The study of</def>
			<word>
				<lang>Modern English</lang>
				<text>biology</text>
				<morpheme>logy</morpheme>
				<def>Study of life</def>
			</word>
		</word>
	</tree>
</etym>
